# Generated by Django 5.1.1 on 2024-10-01 13:06

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='text',
            field=markdownx.models.MarkdownxField(default=3),
            preserve_default=False,
        ),
    ]
