# Generated by Django 5.1.1 on 2024-10-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_project_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='project_backgrounds/'),
        ),
    ]
